### ISSUE TITLE
throw errors when test my own model

### ISSUE THREAD

**Issue by jmssxgp** [NVlabs/SPADE#133]
Network [SPADEGenerator] was created. Total number of parameters: 97.5 million. To see the architecture, do print(network).
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    model = Pix2PixModel(opt)
  File "G:\master\SPADE-master\models\pix2pix_model.py", line 25, in __init__
    self.netG, self.netD, self.netE = self.initialize_networks(opt)
  File "G:\master\SPADE-master\models\pix2pix_model.py", line 96, in initialize_networks
    netG = util.load_network(netG, 'G', opt.which_epoch, opt)
  File "G:\master\SPADE-master\util\util.py", line 208, in load_network
    net.load_state_dict(weights, strict=False)
  File "C:\Users\JMSS\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SPADEGenerator:
        size mismatch for fc.weight: copying a param with shape torch.Size([1024, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([1024, 183, 3, 3]).
        size mismatch for head_0.norm_0.mlp_shared.0.weight: copying a param with shape torch.Size([128, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for head_0.norm_1.mlp_shared.0.weight: copying a param with shape torch.Size([128, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for G_middle_0.norm_0.mlp_shared.0.weight: copying a param with shape torch.Size([128, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for G_middle_0.norm_1.mlp_shared.0.weight: copying a param with shape torch.Size([128, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for G_middle_1.norm_0.mlp_shared.0.weight: copying a param with shape torch.Size([128, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for G_middle_1.norm_1.mlp_shared.0.weight: copying a param with shape torch.Size([128, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_0.norm_0.mlp_shared.0.weight: copying a param with shape torch.Size([128, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_0.norm_1.mlp_shared.0.weight: copying a param with shape torch.Size([128, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_0.norm_s.mlp_shared.0.weight: copying a param with shape torch.Size([128, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_1.norm_0.mlp_shared.0.weight: copying a param with shape torch.Size([128, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_1.norm_1.mlp_shared.0.weight: copying a param with shape torch.Size([128, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_1.norm_s.mlp_shared.0.weight: copying a param with shape torch.Size([128, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_2.norm_0.mlp_shared.0.weight: copying a param with shape torch.Size([128, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_2.norm_1.mlp_shared.0.weight: copying a param with shape torch.Size([128, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_2.norm_s.mlp_shared.0.weight: copying a param with shape torch.Size([128, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_3.norm_0.mlp_shared.0.weight: copying a param with shape torch.Size([128, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_3.norm_1.mlp_shared.0.weight: copying a param with shape torch.Size([128, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_3.norm_s.mlp_shared.0.weight: copying a param with shape torch.Size([128, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).

**Comment by jmssxgp** [comment]
i solved it, you need set the label_nc when test it.
