### ISSUE TITLE
Segfault when --label_nc is incorrect

### ISSUE THREAD

**Issue by kampelmuehler** [NVlabs/SPADE#138]
If I accidentally set --label_nc to a number unequal to the actual number of labels in the label image I'm encountering a Segfault.

```
/opt/conda/conda-bld/pytorch_1614378083779/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [92,0,0], thread: [63,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1614378083779/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [93,0,0], thread: [63,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
Traceback (most recent call last):
  File "train.py", line 40, in <module>
    trainer.run_generator_one_step(data_i)
  File "~/workspace/SPADE/trainers/pix2pix_trainer.py", line 35, in run_generator_one_step
    g_losses, generated = self.pix2pix_model(data, mode='generator')
  File "~/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "~/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "~/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "~/workspace/SPADE/models/pix2pix_model.py", line 45, in forward
    g_loss, generated = self.compute_generator_loss(
  File "~/workspace/SPADE/models/pix2pix_model.py", line 135, in compute_generator_loss
    fake_image, KLD_loss = self.generate_fake(
  File "~/workspace/SPADE/models/pix2pix_model.py", line 191, in generate_fake
    z, mu, logvar = self.encode_z(real_image)
  File "~/workspace/SPADE/models/pix2pix_model.py", line 183, in encode_z
    mu, logvar = self.netE(real_image)
  File "~/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "~/workspace/SPADE/models/networks/encoder.py", line 42, in forward
    x = self.layer1(x)
  File "~/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "~/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "~/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 875, in _call_impl
    result = hook(self, input)
  File "~/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/utils/spectral_norm.py", line 105, in __call__
    setattr(module, self.name, self.compute_weight(module, do_power_iteration=module.training))
  File "~/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/utils/spectral_norm.py", line 84, in compute_weight
    v = normalize(torch.mv(weight_mat.t(), u), dim=0, eps=self.eps, out=v)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered
Exception raised from create_event_internal at /opt/conda/conda-bld/pytorch_1614378083779/work/c10/cuda/CUDACachingAllocator.cpp:733 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7ff5aa8eb2f2 in ~/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7ff5aa8e867b in ~/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x809 (0x7ff5aab44219 in ~/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x54 (0x7ff5aa8d33a4 in ~/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x6e0dda (0x7ff601847dda in ~/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x6e0e71 (0x7ff601847e71 in ~/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #21: __libc_start_main + 0xf3 (0x7ff633fa70b3 in /lib/x86_64-linux-gnu/libc.so.6)

Aborted (core dumped)

```

**Comment by mingyuliutw** [comment]
# New implementation available at imaginaire repository

We have a reimplementation of the SPADE method that is more performant. It is avaiable at [Imaginaire](https://github.com/NVlabs/imaginaire)
