### ISSUE TITLE
FileNotFoundError提示找不到SPADE\datasets\train_label\000000391895.png文件

### ISSUE THREAD

**Issue by cuihua0** [NVlabs/SPADE#31]
当我尝试运行coco_generate_instance_map.py，出现该错误。我找遍了所有下载的文件都没有找到该png。请问怎么办？

U:\Downloads\SPADE\datasets>python373 coco_generate_instance_map.py
annotation file at ./annotations/instances_train2017.json
input label maps at ./train_label/
output dir at ./train_inst/
loading annotations into memory...
Done (t=19.78s)
creating index...
index created!
0 / 118287
D:\python373\lib\site-packages\skimage\io\_io.py:48: UserWarning: `as_grey` has
been deprecated in favor of `as_gray`
  warn('`as_grey` has been deprecated in favor of `as_gray`')
Traceback (most recent call last):
  File "coco_generate_instance_map.py", line 41, in <module>
    img = io.imread(label_name, as_grey=True)
  File "D:\python373\lib\site-packages\skimage\io\_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "D:\python373\lib\site-packages\skimage\io\manage_plugins.py", line 210,
in call_plugin
    return func(*args, **kwargs)
  File "D:\python373\lib\site-packages\imageio\core\functions.py", line 221, in
imread
    reader = read(uri, format, "i", **kwargs)
  File "D:\python373\lib\site-packages\imageio\core\functions.py", line 130, in
get_reader
    request = Request(uri, "r" + mode, **kwargs)
  File "D:\python373\lib\site-packages\imageio\core\request.py", line 126, in __
init__
    self._parse_uri(uri)
  File "D:\python373\lib\site-packages\imageio\core\request.py", line 278, in _p
arse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: 'U:\Downloads\SPADE\datasets\train_label\000000
391895.png'

U:\Downloads\SPADE\datasets>

**Comment by mingyuliutw** [comment]
Please download the full COCO stuff dataset from the official website.
