### ISSUE TITLE
How can I run this on a standalone B&W picture?

### ISSUE THREAD

**Issue by MalharJ** [NVlabs/SPADE#42]
I would like to perform something similar to in the demo as seen here: https://www.youtube.com/watch?v=MXWm6w4E5q0&feature=youtu.be. I have a black and white image as an outline and another photo as the source, and was wondering how I should use SPADE to color my image. Could anyone please help me? Thanks!

**Comment by nkaufie** [comment]
That's an excellent question! I hope this gets answered!

**Comment by taesungp** [comment]
I am not sure what you exactly mean. 

Do you mean coloring black-and-white images like [this](https://richzhang.github.io/colorization/)?

Or do you mean creating realistic photos from simple greyscale outline, like [this][(https://cg.cs.tsinghua.edu.cn/montage/main.htm) or `edges2cats` section of [this](https://affinelayer.com/pixsrv/)?

Both are somewhat different from the scope of SPADE. To achieve any of these methods, you will need to modify the code a bit. Most likely, you will want to remove [the code block](https://github.com/NVlabs/SPADE/blob/master/models/pix2pix_model.py#L117) that creates a one-hot vector from semantic class label. You will want to just use the unmodified B&W input.

**Comment by nkaufie** [comment]
Could you please help me with my problem? 

I'm fairly new to Deep Learning, and I'm trying to solve a colorization problem.
Now I'm using AI Notebooks at Google Cloud, and I have some small images and their BW sketch versions. 

I guess there are no instance maps in this case, and I deleted the one-hot vector block like **taesungp** said in the post above. However, when I try to train my model, it gives this output: 

> train.py --name experiment --dataset_mode custom --label_dir /home/jupyter/SPADE/labels/ --image_dir /home/jupyter/SPADE/images/
> dataset [CustomDataset] of size 541 was created
> Network [SPADEGenerator] was created. Total number of parameters: 92.4 million. To see the architecture, do print(network).
> Network [MultiscaleDiscriminator] was created. Total number of parameters: 1.4 million. To see the architecture, do print(network).
> create web directory ./checkpoints/experiment/web...
> Traceback (most recent call last):
>   File "train.py", line 34, in <module>
>     for i, data_i in enumerate(dataloader, start=iter_counter.epoch_iter):
>   File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 615, in __next__
>     batch = self.collate_fn([self.dataset[i] for i in indices])
>   File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 615, in <listcomp>
>     batch = self.collate_fn([self.dataset[i] for i in indices])
>   File "/home/jupyter/SPADE/data/pix2pix_dataset.py", line 81, in __getitem__
>     instance_path = self.instance_paths[**index**]
> IndexError: **list index out of range**

The code tries to go through the indices of instance_paths, but I used the "--no_instance" option, and I shouldn't even have them. So I have an empty list of instance paths, and I can't enumerate them.

Can you see what's wrong with my code and correct it? 

```
! python -m data.custom_dataset --name experiment --dataset_mode custom --label_dir /home/jupyter/SPADE/labels/ --image_dir /home/jupyter/SPADE/images/ --no_instance

! python train.py --name experiment --dataset_mode custom --label_dir /home/jupyter/SPADE/labels/ --image_dir /home/jupyter/SPADE/images/ 
```

Thanks in advance!

**Comment by MalharJ** [comment]
I guess what I meant was using SPADE to generate art, just like in the youtube video. This is for a class to use Machine Learning to generate art. My input image is here: https://drive.google.com/file/d/1yyNBhciG8O-xkA9LELDx0iCOS1Pd1fJR/view?usp=sharing

What steps would I have to follow to create a landscape using the image above? I tried turning this image into B&W and put it in the `datasets/coco_stuff/val_label`  and  `datasets/coco_stuff/val_inst` directories, but got the following error:

`s/coco_stuff/ --gpu_ids -1
----------------- Options ---------------
             aspect_ratio: 1.0                           
                batchSize: 1                             
      cache_filelist_read: True                          
     cache_filelist_write: True                          
          checkpoints_dir: ./checkpoints                 
        coco_no_portraits: False                         
   contain_dontcare_label: True                          
                crop_size: 256                           
                 dataroot: datasets/coco_stuff/          	[default: ./datasets/cityscapes/]
             dataset_mode: coco                          
          display_winsize: 256                           
                  gpu_ids: -1                            	[default: 0]
                 how_many: inf                           
                init_type: xavier                        
            init_variance: 0.02                          
                  isTrain: False                         	[default: None]
                 label_nc: 182                           
       load_from_opt_file: False                         
                load_size: 256                           
         max_dataset_size: 9223372036854775807           
                    model: pix2pix                       
                 nThreads: 0                             
                     name: coco_pretrained               	[default: label2coco]
                      nef: 16                            
                     netG: spade                         
                      ngf: 64                            
                  no_flip: True                          
              no_instance: False                         
         no_pairing_check: False                         
                   norm_D: spectralinstance              
                   norm_E: spectralinstance              
                   norm_G: spectralspadesyncbatch3x3     
    num_upsampling_layers: normal                        
                output_nc: 3                             
                    phase: test                          
          preprocess_mode: resize_and_crop               
              results_dir: ./results/                    
           serial_batches: True                          
                  use_vae: False                         
              which_epoch: latest                        
                    z_dim: 256                           
----------------- End -------------------
dataset [CocoDataset] of size 1 was created
Network [SPADEGenerator] was created. Total number of parameters: 97.5 million. To see the architecture, do print(network).
Traceback (most recent call last):
  File "test.py", line 36, in <module>
    generated = model(data_i, mode='inference')
  File "/Users/Home/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/Home/Desktop/UCSD/SP2019/what_is_life/Braincorp/SPADE/models/pix2pix_model.py", line 42, in forward
    input_semantics, real_image = self.preprocess_input(data)
  File "/Users/Home/Desktop/UCSD/SP2019/what_is_life/Braincorp/SPADE/models/pix2pix_model.py", line 123, in preprocess_input
    input_semantics = input_label.scatter_(1, label_map, 1.0)
RuntimeError: Invalid index in scatter at /Users/soumith/b101_2/2019_02_08/wheel_build_dirs/wheel_3.6/pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:546`


Any help would be greatly appreciated. Thanks a ton!

**Comment by AugustLee93** [comment]
> Could you please help me with my problem?
> 
> I'm fairly new to Deep Learning, and I'm trying to solve a colorization problem. Now I'm using AI Notebooks at Google Cloud, and I have some small images and their BW sketch versions.
> 
> I guess there are no instance maps in this case, and I deleted the one-hot vector block like **taesungp** said in the post above. However, when I try to train my model, it gives this output:
> 
> > train.py --name experiment --dataset_mode custom --label_dir /home/jupyter/SPADE/labels/ --image_dir /home/jupyter/SPADE/images/
> > dataset [CustomDataset] of size 541 was created
> > Network [SPADEGenerator] was created. Total number of parameters: 92.4 million. To see the architecture, do print(network).
> > Network [MultiscaleDiscriminator] was created. Total number of parameters: 1.4 million. To see the architecture, do print(network).
> > create web directory ./checkpoints/experiment/web...
> > Traceback (most recent call last):
> > File "train.py", line 34, in 
> > for i, data_i in enumerate(dataloader, start=iter_counter.epoch_iter):
> > File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 615, in **next**
> > batch = self.collate_fn([self.dataset[i] for i in indices])
> > File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 615, in 
> > batch = self.collate_fn([self.dataset[i] for i in indices])
> > File "/home/jupyter/SPADE/data/pix2pix_dataset.py", line 81, in **getitem**
> > instance_path = self.instance_paths[**index**]
> > IndexError: **list index out of range**
> 
> The code tries to go through the indices of instance_paths, but I used the "--no_instance" option, and I shouldn't even have them. So I have an empty list of instance paths, and I can't enumerate them.
> 
> Can you see what's wrong with my code and correct it?
> 
> ```
> ! python -m data.custom_dataset --name experiment --dataset_mode custom --label_dir /home/jupyter/SPADE/labels/ --image_dir /home/jupyter/SPADE/images/ --no_instance
> 
> ! python train.py --name experiment --dataset_mode custom --label_dir /home/jupyter/SPADE/labels/ --image_dir /home/jupyter/SPADE/images/ 
> ```
> 
> Thanks in advance!

Hi @nkaufie , did you solve the problem? I got the same situation with you. I was trying to do RGB2RGB translated task, but struggling with this error. Any helps I will very appreciate it ! Thanks
